### PR TITLE
Fix video recording for HTC One M9 Devices (hima*)

### PR DESCRIPTION
**Pull request by armills**

### CODE REVIEW

**Comment by rc420head** [comment]
Didn't work for me, is there another part I'm missing?

**Comment by armills** [comment]
Going to have to put together a more complete pull request, per the discussion here: http://forum.xda-developers.com/one-m9/general/bounty-htc-one-m9-aosp-cm12-1-camera-t3193175/page22#post63371845

**Comment by armills** [comment]
Added a cleaned up version of the camera hack. Should replace this commit: https://github.com/CandyRoms/frameworks_av/commit/97dc708f1cb6cc8c8134011c46b6363aec7af7e6

**Comment by rc420head** [comment]
Ok I'll fix it up when I get home from work

**Comment by rc420head** [comment]
This breaks camera on other devices, is this still needed? Can we do it in device tree?

**Comment by armills** [comment]
It looks like Rashed is working an a separate patch to move this to the device tree. Although that has its own drawbacks, it really is a device specific hack, and belongs there. It's probably safe to close this pull request, and use the changes there.

http://review.cyanogenmod.org/#/c/114153/

**Pull request closed without merging**
